### ISSUE TITLE
perl grep obliterates subject list in perl v5.18.2?

### ISSUE THREAD

**Issue by pipitone** [CobraLab/lpba40-local-civet-measures#1]
@awheel24 finds that running version eee7a8fd7ae8a9f9edc1f50250e0c05e1d6681d6 of `get-lpba40-CT-SA.pl` results in an empty output CSV (well, empty except for the headers). Some print line debugging reveals that the subject folders are read in correctly in line 55, but the `grep` calls in 56-57 leave the `@subjects` list empty. Guh? 

This is using Perl v5.18.2 on Xubuntu 14.04. 

To work around this problem, I removed the grep calls, and inside the `foreach` loop on line 82, I inserted: 

``` perl
if (($subject eq 'QC') or ($subject eq 'References.txt')) {
  next;
}
```

**Comment by gdevenyi** [comment]
How odd, change looks good to me, PR?
